



SELECT * FROM admins;


CREATE SEQUENCE AirportSeq
    START WITH 1
    INCREMENT BY 1;
CREATE SEQUENCE FlightSeq
    START WITH 1
    INCREMENT BY 1;
CREATE SEQUENCE PassengerSeq
    START WITH 1
    INCREMENT BY 1;
CREATE SEQUENCE ScheduleSeq
    START WITH 1
    INCREMENT BY 1;
CREATE SEQUENCE BookingSeq
    START WITH 1
    INCREMENT BY 1;
